name: awani_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  step_progress_indicator: ^0.1.0+1
  flutter_masked_text: ^0.8.0
  font_awesome_flutter: ^8.8.1
  dropdown_formfield: ^0.1.2
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  equatable: ^1.2.5
  bloc: ^6.0.3
  rxdart: ^0.24.1
  sqflite: any  
  path_provider: ^1.6.18
  shared_preferences: ^0.5.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/back.png
    - assets/logo.png
    - assets/loading.png
    - assets/Tableware2.png
    - assets/suiv.png
    - assets/points1.png
    - assets/SoupBowl.png
    - assets/BowlPlate.png
    - assets/twitter.png
    - assets/Arrow_simple_rightt.png
    - assets/kuwait.png
    - assets/qatar-flag.png
    - assets/Triangle@2x.png
    - assets/RoundRectangle.png
    - assets/tick.png
    - assets/flesh.png
    - assets/bowl.png
    - assets/bowl3.png
    - assets/forn.jpg
    - assets/amsinox.png
    - assets/favorite.png
    - assets/grilla.png
    - assets/kavalkad.png
    - assets/ikea.png
    - assets/hemlagad.png
    - assets/sensuel.png
    - assets/vardagen.png
    - assets/tefal.png
    - assets/ikeaGrand.png
    - assets/favoriteMoy.png
    - assets/ikea1.png
    - assets/ikea2.png
    - assets/ikea3.png
    - assets/ikea4.png
    - assets/arrowMoy.png
    - assets/arrowMoyCopie.png
    - assets/tickSmall.png
    - assets/ikeaMoy.png
    - assets/Arrow.png
    - assets/ArrowCopie.png
    - assets/remove.png
    - assets/plateau.png
    - assets/switchoff.png
    - assets/switchsmalloff.png
    - assets/plat.png
    - assets/grila.png
    - assets/knife.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FFAlamaO
      fonts:
        - asset: assets/fonts/FFAlamaO-RegularO.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
